[package]
name = "node_example"
version = "0.1.0"
edition = "2024"

[dependencies]
bee_message = { path = "../../honeybee_core/bee_message" }
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
rand = "0.9.2"